version: "3.3"

services:

  elasticsearch:
    image: kamilskomro/challenge-es:1.0
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - challenge-network
    environment:
      - discovery.type=single-node

  keycloak:
    image: kamilskomro/kc:1.1
    ports:
      - "8088:8080"
    networks:
      - challenge-network

  ui:
    image: kamilskomro/challenge-ui:1.1
    ports:
      - "4200:80"
    networks:
      - challenge-network

  api:
    image: kamilskomro/challenge-backend:1.1
    ports:
      - "8080:8080"
    networks:
      - challenge-network
    environment:
      KEYCLOAK_HOST: keycloak
      KEYCLOAK_PORT: 8080
      ELS_HOST: elasticsearch
      ELS_PORT: 9200

  papercut:
    image: jijiechen/papercut:20180425042132
    ports:
      - "25:25"
      - "37408:37408"
    networks:
      - challenge-network

networks:
  challenge-network:
    driver: bridge
    ipam:
      driver: default